#!/usr/bin/env python3
"""
Creates ONE Google Doc: "Felix Pago WhatsApp Top-Up: End-to-End Flow From Real Screens".

Second-pass competitive teardown of Felix Pago's WhatsApp recarga (mobile top-up)
journey, rebuilt from real captured screens rather than documentation: Felix's own
production screenshots, 36 downloaded videos (official channel, TikTok, third-party
walkthroughs, a Finovate stage demo), the X and Instagram launch carousels, and the
native app store listings. Every screen was catalogued by one agent and re-read by an
adversarial verifier before it was used here.

Images are served from the public GitHub repo (the Docs API needs public URLs and IDT
Drive sharing is org-restricted). Commit and push the felix_evidence/ folder before
running this script.

Content blocks are generated by build_content() in felix_recarga_evidence_content.py so
the same source of truth feeds the HTML artifact and this document.
"""

import time
from pathlib import Path

from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build

from linkify_refs import LINK_MAP, linkify
from felix_recarga_evidence_content import TITLE, BLOCKS, TABLES, IMAGES, EXTRA_LINKS, VERDICT_COLOR

SCOPES = [
    "https://www.googleapis.com/auth/documents",
    "https://www.googleapis.com/auth/drive",
]
BASE = Path(__file__).parent
CREDS_FILE = BASE / "credentials.json"
TOKEN_FILE = BASE / "token.json"
RAW_BASE = "https://raw.githubusercontent.com/tanaka-idt/IDT-Claude/main/felix_evidence/"

STYLE_MAP = {"h1": "HEADING_1", "h2": "HEADING_2", "h3": "HEADING_3", "h4": "HEADING_4",
             "p": "NORMAL_TEXT", "b": "NORMAL_TEXT", "n": "NORMAL_TEXT",
             "cap": "NORMAL_TEXT", "quote": "NORMAL_TEXT"}


def get_credentials():
    creds = None
    if TOKEN_FILE.exists():
        creds = Credentials.from_authorized_user_file(str(TOKEN_FILE), SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(str(CREDS_FILE), SCOPES)
            creds = flow.run_local_server(port=0)
        TOKEN_FILE.write_text(creds.to_json())
    return creds


def u16(s):
    """Docs API indices count UTF-16 code units, so emoji count as two."""
    return len(s.encode("utf-16-le")) // 2


def build_requests(blocks):
    """Text blocks -> batchUpdate requests. Tables and images are placeholders
    ([[MARKER]]) that are replaced afterwards, because insertTable/insertInlineImage
    shift indices unpredictably."""
    reqs, cur = [], 1
    for kind, text in blocks:
        if kind in ("table", "image"):
            line = f"[[{text}]]\n"
            reqs.append({"insertText": {"location": {"index": cur}, "text": line}})
            cur += u16(line)
            continue

        line = text + "\n"
        reqs.append({"insertText": {"location": {"index": cur}, "text": line}})
        para = {"namedStyleType": STYLE_MAP[kind]}
        fields = "namedStyleType"
        if kind == "cap":
            para["alignment"] = "CENTER"
            fields += ",alignment"
        if kind == "quote":
            para["indentStart"] = {"magnitude": 24, "unit": "PT"}
            fields += ",indentStart"
        reqs.append({"updateParagraphStyle": {
            "range": {"startIndex": cur, "endIndex": cur + u16(line)},
            "paragraphStyle": para, "fields": fields}})

        if kind == "b":
            reqs.append({"createParagraphBullets": {
                "range": {"startIndex": cur, "endIndex": cur + u16(line)},
                "bulletPreset": "BULLET_DISC_CIRCLE_SQUARE"}})
        if kind == "n":
            reqs.append({"createParagraphBullets": {
                "range": {"startIndex": cur, "endIndex": cur + u16(line)},
                "bulletPreset": "NUMBERED_DECIMAL_ALPHA_ROMAN"}})
        if kind == "cap":
            reqs.append({"updateTextStyle": {
                "range": {"startIndex": cur, "endIndex": cur + u16(text)},
                "textStyle": {"italic": True,
                              "fontSize": {"magnitude": 9, "unit": "PT"}},
                "fields": "italic,fontSize"}})
        if kind == "quote":
            reqs.append({"updateTextStyle": {
                "range": {"startIndex": cur, "endIndex": cur + u16(text)},
                "textStyle": {"weightedFontFamily": {"fontFamily": "Roboto Mono"},
                              "fontSize": {"magnitude": 9.5, "unit": "PT"}},
                "fields": "weightedFontFamily,fontSize"}})
        # "Lead: rest" bolding for bullets and paragraphs that use a double-space colon lead.
        if kind in ("b", "p") and "  ::  " in text:
            lead = text.split("  ::  ")[0]
            reqs.append({"updateTextStyle": {
                "range": {"startIndex": cur, "endIndex": cur + u16(lead)},
                "textStyle": {"bold": True}, "fields": "bold"}})
        cur += u16(line)
    return reqs


def batched(docs, doc_id, reqs, size=40):
    for i in range(0, len(reqs), size):
        docs.documents().batchUpdate(
            documentId=doc_id, body={"requests": reqs[i:i + size]}).execute()
        time.sleep(0.25)


def para_text(el):
    if "paragraph" not in el:
        return ""
    return "".join(e.get("textRun", {}).get("content", "")
                   for e in el["paragraph"]["elements"])


def find_marker(docs, doc_id, marker):
    doc = docs.documents().get(documentId=doc_id).execute()
    for el in doc["body"]["content"]:
        if para_text(el).strip() == f"[[{marker}]]":
            return el["startIndex"], u16(para_text(el)), doc
    return None, None, doc


def insert_table(docs, doc_id, marker, data):
    idx, plen, _ = find_marker(docs, doc_id, marker)
    if idx is None:
        print(f"  ! placeholder {marker} not found")
        return False

    rows, cols = len(data), len(data[0])
    docs.documents().batchUpdate(documentId=doc_id, body={"requests": [
        {"deleteContentRange": {"range": {"startIndex": idx,
                                          "endIndex": idx + plen - 1}}},
        {"insertTable": {"location": {"index": idx}, "rows": rows,
                         "columns": cols}},
    ]}).execute()
    time.sleep(1.0)

    doc = docs.documents().get(documentId=doc_id).execute()
    table_el = None
    for el in doc["body"]["content"]:
        if "table" in el and el["startIndex"] >= idx - 2:
            table_el = el
            break
    if table_el is None:
        print(f"  ! table {marker} not found after insert")
        return False

    cells = []
    for r, row in enumerate(table_el["table"]["tableRows"]):
        for c, cell in enumerate(row["tableCells"]):
            cells.append((cell["content"][0]["startIndex"], r, c))

    reqs = []
    for start, r, c in sorted(cells, reverse=True):
        txt = data[r][c]
        reqs.append({"insertText": {"location": {"index": start}, "text": txt}})
        if r == 0:
            reqs.append({"updateTextStyle": {
                "range": {"startIndex": start, "endIndex": start + u16(txt)},
                "textStyle": {"bold": True}, "fields": "bold"}})
        elif txt in VERDICT_COLOR and c == 0:
            red, green, blue = VERDICT_COLOR[txt]
            reqs.append({"updateTextStyle": {
                "range": {"startIndex": start, "endIndex": start + u16(txt)},
                "textStyle": {"bold": True, "foregroundColor": {"color": {
                    "rgbColor": {"red": red, "green": green, "blue": blue}}}},
                "fields": "bold,foregroundColor"}})
    batched(docs, doc_id, reqs, size=40)
    return True


def insert_image(docs, doc_id, marker, fname, width, nw, nh):
    idx, plen, _ = find_marker(docs, doc_id, marker)
    if idx is None:
        print(f"  ! placeholder {marker} not found")
        return False
    height = round(width * nh / nw, 1)
    docs.documents().batchUpdate(documentId=doc_id, body={"requests": [
        {"deleteContentRange": {"range": {"startIndex": idx,
                                          "endIndex": idx + plen - 1}}},
        {"insertInlineImage": {
            "location": {"index": idx}, "uri": RAW_BASE + fname,
            "objectSize": {"width": {"magnitude": width, "unit": "PT"},
                           "height": {"magnitude": height, "unit": "PT"}}}},
        {"updateParagraphStyle": {
            "range": {"startIndex": idx, "endIndex": idx + 1},
            "paragraphStyle": {"namedStyleType": "NORMAL_TEXT",
                               "alignment": "CENTER"},
            "fields": "namedStyleType,alignment"}},
    ]}).execute()
    time.sleep(0.4)
    return True


def main():
    creds = get_credentials()
    docs = build("docs", "v1", credentials=creds)
    drive = build("drive", "v3", credentials=creds)

    doc = docs.documents().create(body={"title": TITLE}).execute()
    doc_id = doc["documentId"]
    print(f"Created doc: {doc_id}")

    reqs = build_requests(BLOCKS)
    batched(docs, doc_id, reqs)
    print(f"Inserted {len(reqs)} text requests")

    for marker, data in TABLES:
        ok = insert_table(docs, doc_id, marker, data)
        print(f"  table {marker}: {'ok' if ok else 'FAILED'} ({len(data) - 1} rows)")

    for marker, fname, w, nw, nh in IMAGES:
        ok = insert_image(docs, doc_id, marker, fname, w, nw, nh)
        print(f"  image {marker}: {'ok' if ok else 'FAILED'} ({fname})")

    linkify(docs, doc_id, {**LINK_MAP, **EXTRA_LINKS})

    drive.permissions().create(
        fileId=doc_id,
        body={"role": "writer", "type": "domain", "domain": "idt.net"},
    ).execute()

    url = f"https://docs.google.com/document/d/{doc_id}/edit"
    print(f"\nDone: {url}")
    return url


if __name__ == "__main__":
    main()
